### ISSUE TITLE
TypeError: UniAnimateNode.generate() got an unexpected keyword argument 'pose_dir'

### ISSUE THREAD

**Issue by zhenyuanzhou** [AIFSH/ComfyUI-UniAnimate#6]
!!! Exception during processing!!! UniAnimateNode.generate() got an unexpected keyword argument 'pose_dir'
Traceback (most recent call last):
  File "F:\ComfyUI-master\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "F:\ComfyUI-master\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "F:\ComfyUI-master\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
TypeError: UniAnimateNode.generate() got an unexpected keyword argument 'pose_dir'

Prompt executed in 0.00 seconds

**Comment by zhenyuanzhou** [comment]
![Uploading 屏幕截图 2024-07-03 203417.png…]()

**Comment by zhenyuanzhou** [comment]
The problem is as follows:
import folder_paths 
......
# pose_dir = os.path.join(output_dir,"UniAnimate","source_video")

I believe the problem is from these two codes
